version: '3.4'
services:
  flask:
    container_name: flask

    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - "5000:5000"
    restart: always
    networks:
      - default
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    restart: always
    tty: true
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - flask
    networks:
      - default
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  default:
    driver: bridge
