version: '3'
services:
  flask-container:
    image: "flask-app-image"
    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - 8163:8163
    volumes:
      - ./:/flask/app
  nginx:
    container_name: "nginx-container"
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - 8080:80
      - 8443:443
    links:
      - "flask-container"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
